!THIS PROGRAM FINDING ROOT OF A QUADRATIC EQUATION
PROGRAM QUAD_EQN
 IMPLICIT NONE
 REAL::A1,A2,A3,X1,X2
 INTEGER::FLAG
 
 PRINT*,"ENTER THE COEFFICIENTS OF X IN THE EQUATION"
  READ*,A1,A2,A3
  CALL SOLVE(A1,A2,A3,X1,X2,FLAG)
IF(FLAG ==0)THEN
 PRINT*,"FIRST ROOT:",X1,"SECOND ROOT:",X2
ELSE
 PRINT 10,"FIRST ROOT:",X1,"+i",X2,"SECOND ROOT:",X1,"-i",X2
 10 FORMAT(2X,A11,F6.2,A2,F6.2,2X,A12,F6.2,A2,F6.2)
ENDIF
END PROGRAM QUAD_EQN



SUBROUTINE SOLVE(A1,A2,A3,X1,X2,FLAG)
 IMPLICIT NONE
 REAL,INTENT(IN)::A1,A2,A3
 REAL,INTENT(OUT)::X1,X2
 INTEGER,INTENT(OUT)::FLAG
 REAL::TEMP

  FLAG=0 
  TEMP=A2*A2-4*A1*A3

 IF(TEMP > 0)THEN
  X1=(-A2-SQRT(REAL(TEMP)) )/(2*A1)
  X2=(-A2+SQRT(REAL(TEMP)) )/(2*A1)
 ELSEIF(TEMP<0)THEN
  FLAG=1
  X1=-A2/2*A1
  X2=SQRT(REAL(-TEMP))/2*A1
 ELSE
  X1=-A2/A1
  X2=-A2/A1
 ENDIF
 

END SUBROUTINE

